export const ENDPOINTS = {
  companies: "/companies/",
  bankAccounts: "/bank-accounts/",
  distributors: "/transactions/distributors/",
  partners: "/transactions/partners/",
  incoming: "/transactions/incoming/",
  outgoing: "/transactions/outgoing/",
  expenses: "/transactions/expenses/",
  adjustments: "/transactions/balance-adjustments/",
  reports: "/transactions/reports/period/",
  denXanDaily: "/transactions/den-xan/daily/",
  denXanExpenses: "/transactions/den-xan/expenses/",
  denXanReport: "/transactions/den-xan/report/",
  denXanCash: "/transactions/den-xan/cash/",
  clearingPeople: "/clearing/people/",
  clearingCompanies: "/clearing/companies/",
  clearingOperations: "/clearing/operations/",
  clearingReport: "/clearing/report/",
};
